sudo: false

env:
  global:
  - secure: "KUxLiIAKPfnLPxsSC8Dv05Sr0vIISnfgqelrgbvYQBskfzr7h4MVkCn5Ckk8hYcAd9zHX+9jwputUcS8es3iy7Z79UdBliozydiVTUDSbPcEDeUzxuCRBoySdJ+VGttyWfxwpgxF3mNV3ayJY15p7B7b+9Begvzd/vBhBTVXQWulckh3DZWCDI9TZ4fidXY0GcnRk4ESP2Rz6m8iTxjNwDTzEFFK6g9PdO3hoS9NFVGTl24KrGzhpa5BfbZ82GIeoXHFgspuzI5Fp9Ze7n9fwqv2Pf4DGiVei8sKaNCHZ1YhoO5S0syhrhQrAA3dNN/xHuA1YUowGSszqRImbjcBws1Ezf9peWUIMmd0TBJxP3ViSh8v/p8/INJYwwdiLUVKYkcSUrLHWNH24CvUvDPy6Pgx22iJj6H4AxmiZzOekiqtuG/q/eGVBnwJQNgbxhiqLV/MjZ2UmIDm3Unm4VOYGHBPIS5fmlnk/oHTA6aHWQ1fhN8RbGc4abTQ9h2bVOdw43hxy+XobwpmIsElObrZaU02qJfYQCNXIuth2+pQ1SCY2ZDTrLj7qer6OxbPbQBzbdDwYN9qDXd6Lm7GxWJK2eFh31HqzibHBXy+z+5YZufdpcysp4cYXF4K56RNdnnZIMz65nwJKJMrGYwumGwrmzR60lX/iepJ6Q+Q5Bf+zuE="
  - GH_REF: github.com/karelhala/jenkins-test.git
  - GH_BRANCH: gh-pages

language: node_js

node_js:
  - '5.10.1'
npm:
  - '3.8.3'
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - bash ./build.sh
  - bash ./.travis-deploy.sh
