sudo: false

env:
  global:
  - secure: "WuT6aEP94rObMmXexC+H9dco7t1WafeHQaexVD8Ims/ghtnn6/L35gdvb9HrUhde5+Zbbc0PqUBqnSgSRhDE3ZMl9DNJkYLgFzcKBB5fJIl7VM3msAIL9VUWhclHhrhCYLZdt7OFmprE1oMQnrtYcEV2oxsuMMuvy6onhaKEO81oFo+Z7mhz5CHv6DoKjJceOD86xVP2lnrPPbkP+GD9ksGuZYtIxsCxtt9S5L6oMOu1VLszvqnaXN3FdSTQTf7SySThmsIHVLTm/tvyeiTPtva6L1GwDDS5BePneWJ4R7osbY9PZoGhtEV9bdD8vCN8BxOza/9+273T2njj2+E0pH4wESsN/IYFqFJiFdIJL3A2Al3zqORsunIagZk2aZNwV07BQhTv8ZKVjy66P5hRrqBHFcldhXrVNFhGPTaCnoCj3E3WNTNOlO54Y+I4r3uomLtVLFbBUu5zYmZUXqWEEzriOc4yr1gflPfD1fCqmjliqWR2I7dFUN8qcQt/PEHuZ4U00CSZovCjSP+uWrt7r3xIki6QmH8LqIwXgPnwxSDC+FN7vyZN+2V5R0plioEczi/dRWAwTQaFqzUjciYm7gG4SV/6r+JZqDz0CQHexKxG4Go61UxKyKFBDOnGmevUF3259OxqfXsK+9x/PV9T1jVIRXx6IW4EuVGf27RNmVA="
  - GH_REF: github.com/karelhala/jenkins-test.git
  - GH_BRANCH: gh-pages

language: node_js

node_js:
  - '5.10.1'
npm:
  - '3.8.3'
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - bash ./build.sh
  - bash ./.travis-deploy.sh
